api_key = "*********your api_key here**********"
database_key = "*******your database_key_im using pinecone****"
directory_path = "C:\\Users\\14375\\openai-env\\pythonProject1\\content"

embedding_model = "text-embedding-3-small"  #can choose any embedding models from open-ai "https://platform.openai.com/docs/guides/embeddings"eg:text-embedding-3-small and text-embedding-3-large
AI_model = "gpt-3.5-turbo-0125" #can use any open ai models refer "https://platform.openai.com/docs/models/overview"

#place this file in .streamlit folder which should be inside your project folder##

